🔥 Add support for git submodules
lunakoly/QuickLink pull request #12
Opened 2022-11-07 18:27 UTC by akhilerm

generate link to submodule repository if the selected file is from a git submodule

Signed-off-by: Akhil Mohan <akhilerm@gmail.com>

2022-11-07 18:29 UTC, akhilerm commented
I have kept the release at 1.0.5 itself since I didnt see a release generated for the last commit, i.e support for spaces

2022-11-09 13:49 UTC, akhilerm commented
@lunakoly Can this change be reviewed?

2022-11-09 18:13 UTC, lunakoly commented
Sure, I wrote 2 comments

2022-11-10 01:22 UTC, akhilerm commented
@lunakoly  Are the comments not submitted? I cant see them on the changes

2022-11-10 14:49 UTC, lunakoly requested changes

2022-11-10 14:50 UTC, lunakoly commented
> @lunakoly Are the comments not submitted? I cant see them on the changes

Oh, I'm sorry, I didn't notice that. And [it seems I'm not the only one](https://github.com/community/community/discussions/10369)...

2022-11-12 07:20 UTC, akhilerm commented on src/main/kotlin/com/github/lunakoly/quicklink/repository/RepositoryInfoBuilders.kt
> +    val repositories = ArrayList<RepositoryInfo>()
Done.

2022-11-12 07:20 UTC, akhilerm commented on src/main/kotlin/com/github/lunakoly/quicklink/actions/CopyLineLinkAction.kt
> +        val repositoryInfo = repositoryInfoList.find {
Done

2022-11-12 09:26 UTC, merged