Support custom domains
lunakoly/QuickLink pull request #6
Opened 2021-07-31 23:54 UTC by GetRhymes

In this update will be add support custom domains. We can use private or custom domain, which based on GitLab or GitHub domains and generate link for need line.

Progress: 
- [ ] Settings menu 
- [ ] Storage custom domains
- [ ] Changing custom domains
- [ ] Link builder
- [ ] Сode Refactoring
- [ ] Fix small bugs
- [ ] Test

2021-08-02 21:27 UTC, lunakoly commented
Please, move `ui`-components to a proper place, because a package named `helpers` doesn't really reflect their purpose. `helpers` might be fine for a collection of random tiny functions, but not for complicated `ui`-components

2021-08-02 21:27 UTC, lunakoly commented
Also make sure the `Build` pipeline works fine for all commits you intent to merge into `main`

2021-08-05 17:20 UTC, lunakoly requested changes

2021-08-07 20:29 UTC, lunakoly commented
Any progress on the thing?

2021-08-11 19:41 UTC, GetRhymes commented on src/main/kotlin/com/github/lunakoly/quicklink/settings/helpers/DomainToUrlBuildersTableModel.kt
> +    override fun addTableModelListener(p0: TableModelListener?) {
We need this method, because we should override them

2021-08-11 21:20 UTC, merged